### ISSUE TITLE
Build fails with not finding esp_littlefs.h

### ISSUE THREAD

**Issue by caveman99** [Othernet-Project/Dreamcatcher#19]
Both the esp32 and esp32s2 build fail with similar error messages: 

../components/arduino/libraries/LITTLEFS/src/LITTLEFS.cpp:25:10: fatal error: esp_littlefs.h: No such file or directory
 #include "esp_littlefs.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.

It's strange that this is happening in a submodule. Fresh clean checkout made this morning

**Comment by chegewara** [comment]
https://github.com/Othernet-Project/Dreamcatcher#possible-runtime-issues

> some changes may be required in https://github.com/espressif/arduino-esp32/blob/idf-release/v4.2/CMakeLists.txt, in this repository is included file with fixed content: https://github.com/chegewara/dreamcatcher4/blob/master/CMakeLists.txt_arduino-esp32

**Comment by caveman99** [comment]
Thanks, i think i did that the first time around but reverted that 'local' change when the new "git pull" wouldn't go through. It's building now.
