### ISSUE TITLE
Update or patch Arduino Libs for I2C support

### ISSUE THREAD

**Issue by caveman99** [Othernet-Project/Dreamcatcher#26]
When compiling for an actual DC4 Board and not a test mule the I2C bus does not get enabled and causes a subsequent kernel panic. This is due to a missing fix (by @chegewara ) in the Arduino Libs being pulled in as submodule from a fixed point-in-time in January 2021, while the fix was only merged in April 2021. We should either update the lib to 2.0.0alpha which includes the fix (and many other possibly breaking changes) or document the changed file in the README similar to the updated CMake File.

Reference: https://github.com/espressif/arduino-esp32/pull/4996/commits/baaf9f2a15c061f0e53b785518a03438f8d0fa0e

**Comment by chegewara** [comment]
https://github.com/Othernet-Project/Dreamcatcher#possible-runtime-issues

> there is change in esp-idf i2c and arduino-esp32 has not been updated yet, this requires to update esp32-hal-i2c.c line 1819 with code i2c_config_t conf = {0};

Arduino-esp32 v2.0.0-alpha is very unstable yet and we wont update to it yet.

**Comment by caveman99** [comment]
Sometimes it helps to actually read the readme, sorry :-). I agree 2.0.0 is not production ready.
