### ISSUE TITLE
Enable debug output/logging on USB-Serial

### ISSUE THREAD

**Issue by caveman99** [Othernet-Project/Dreamcatcher#28]
The actual Dreamcatcher 4 Board does not have a hardware UART-USB converter (like the NodeMCU type boards have) but uses the onchip USB interface. To send serial debug and log output over this interface instead of UART0 change the following in the SDK Config files:

```
CONFIG_ESP_CONSOLE_USB_CDC=y (uncomment this and set to y)
# CONFIG_ESP_CONSOLE_UART is not set (comment this out)
```

In case we need the USB interface for OTG stuff later, switch to the TinyUSB lib instead which provides similar functionality.

**Comment by Tysonpower** [comment]
Where you able to make this working? I set the output of the log in the menuconfig to USB but my PC does not connect to it, it just says "Couldn't recognice USB Device"

**Comment by caveman99** [comment]
Yes, this is working for me - however my windows PC recognizes the debug serial on another virtual COM than the programming interface started up by pressing the button on power up. e.g. programming is COM3, debug is COM4 for me.

**Comment by Tysonpower** [comment]
Okay works, looks like the Newest Board won't run from USB Power, with an older one it works. I will include it in the next Commit.
