### ISSUE TITLE
solar panel

### ISSUE THREAD

**Issue by srem1** [Othernet-Project/Dreamcatcher#41]
Is possible add solar panel on motherboard and charger to 18650 or lipo?

**Comment by syedkarim** [comment]
Those are expensive components and I'm not sure how many customers would actually use it. It's easy enough to just buy a solar/battery system and connect it to the Dreamcatcher.

**Comment by srem1** [comment]
expensive? https://hackaday.io/project/164682-a-cheap-and-dangerous-garden-light-boost-converter
this board not consumpt more power. this is tiny consumption dev.

**Comment by Tysonpower** [comment]
thast just false, a attiny doesn't consume much power at all, the ESP32 needs a lot more power and will have quite high power spikes with up to 2A at 3.3V.

So yeah, the dc would need a decent mppt or simlar chip and a decent lion circuit to charge a good battery, thats to much for now as syed stated.
