### ISSUE TITLE
Messages are aren't always most recent on web view.

### ISSUE THREAD

**Issue by Anglac** [Othernet-Project/Dreamcatcher#51]
Version 1.0.8 getMessages() javascript function isn't pulling the newest date worth of messages.

I believe this is fixed to get the newest date (at least worked for me):

`// get newest messages from backend
async function getMessages() {
    console.log('getMessages started....')

    let folders = JSON.parse(synchronousRequest('/files/messages/'))
    folders = folders.sort((a,b)=> {
    var a1 = a.name.toLowerCase();
    var b1 = b.name.toLowerCase();
    return a1>b1 ?-1:a1< b1? 1 :0;
    })
    let files = []
    for (const folder of folders) {
        if(folder.name != "Up"){
            let newFiles = JSON.parse(synchronousRequest(folder.path+'/'))
            files = files.concat(newFiles)
            if (files.length >= 4) {
                files.reverse()
                files = files.slice(0, 4)
                break
            }
        }
    }
`

Same sorting might need to be done with time as I did with date?  Not sure if the json is supposed to be coming out in order of creation date or not but it wasn't on my device.

**Comment by Tysonpower** [comment]
Thanks for the Tipp, did the sorting not work in general or just at special ocasions.

For example if todays folder only has one file so two folders need to be searched.

**Comment by Anglac** [comment]
Seems like it's just the sorting coming out of /files/messages in general.

This is the json from my machine right now:

`[{"path":"/files/messages/..", "dir":1,"name":"Up", "size":"0"}, 
{"path":"/files/messages/2023-12-30", "dir":1,"name":"2023-12-30", "size":"0"}, 
{"path":"/files/messages/2024-01-02", "dir":1,"name":"2024-01-02", "size":"0"}, 
{"path":"/files/messages/2024-01-06", "dir":1,"name":"2024-01-06", "size":"0"}, 
{"path":"/files/messages/2023-12-28", "dir":1,"name":"2023-12-28", "size":"0"}, 
{"path":"/files/messages/2023-12-29", "dir":1,"name":"2023-12-29", "size":"0"}]`

Existing code would look at 12/29 and then go back to 12/28 if it needed to go back a folder...

I don't leave it running 24/7 so you can see I'm missing a few dates, but I don't think that would be the cause issues, but sorting "alphabetically" by name and the existing year-month-day format got it in the right order.

json from "/files/messages/2024-01-06/" seems to be in chronological order for me:
 
`[{"path":"/files/messages/2024-01-06/..", "dir":1,"name":"Up", "size":"0"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_16_40.txt.tbz2", "dir":0,"name":"2024-01-06_16_40.txt.tbz2", "size":"8818"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_16_50.txt.tbz2", "dir":0,"name":"2024-01-06_16_50.txt.tbz2", "size":"8157"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_16_54_tags.txt.tbz2", "dir":0,"name":"2024-01-06_16_54_tags.txt.tbz2", "size":"343"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_16_55.txt.tbz2", "dir":0,"name":"2024-01-06_16_55.txt.tbz2", "size":"8377"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_16_58.txt.tbz2", "dir":0,"name":"2024-01-06_16_58.txt.tbz2", "size":"289"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_17_00_tags.txt.tbz2", "dir":0,"name":"2024-01-06_17_00_tags.txt.tbz2", "size":"1378"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_17_05.txt.tbz2", "dir":0,"name":"2024-01-06_17_05.txt.tbz2", "size":"7497"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_17_10.txt.tbz2", "dir":0,"name":"2024-01-06_17_10.txt.tbz2", "size":"7717"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_17_55_tags.txt.tbz2", "dir":0,"name":"2024-01-06_17_55_tags.txt.tbz2", "size":"323"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_17_55.txt.tbz2", "dir":0,"name":"2024-01-06_17_55.txt.tbz2", "size":"8157"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_18_00_tags.txt.tbz2", "dir":0,"name":"2024-01-06_18_00_tags.txt.tbz2", "size":"1635"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_18_05.txt.tbz2", "dir":0,"name":"2024-01-06_18_05.txt.tbz2", "size":"7277"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_18_10.txt.tbz2", "dir":0,"name":"2024-01-06_18_10.txt.tbz2", "size":"7277"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_00_tags.txt.tbz2", "dir":0,"name":"2024-01-06_19_00_tags.txt.tbz2", "size":"1452"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_30.txt.tbz2", "dir":0,"name":"2024-01-06_19_30.txt.tbz2", "size":"6397"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_40.txt.tbz2", "dir":0,"name":"2024-01-06_19_40.txt.tbz2", "size":"7277"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_45.txt.tbz2", "dir":0,"name":"2024-01-06_19_45.txt.tbz2", "size":"7057"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_50.txt.tbz2", "dir":0,"name":"2024-01-06_19_50.txt.tbz2", "size":"7497"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_54_tags.txt.tbz2", "dir":0,"name":"2024-01-06_19_54_tags.txt.tbz2", "size":"295"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_19_55_tags.txt.tbz2", "dir":0,"name":"2024-01-06_19_55_tags.txt.tbz2", "size":"553"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_20_15.txt.tbz2", "dir":0,"name":"2024-01-06_20_15.txt.tbz2", "size":"7717"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_20_35.txt.tbz2", "dir":0,"name":"2024-01-06_20_35.txt.tbz2", "size":"7497"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_20_40.txt.tbz2", "dir":0,"name":"2024-01-06_20_40.txt.tbz2", "size":"7057"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_20_55_tags.txt.tbz2", "dir":0,"name":"2024-01-06_20_55_tags.txt.tbz2", "size":"300"}, 
{"path":"/files/messages/2024-01-06/2024-01-06_21_00_tags.txt.tbz2", "dir":0,"name":"2024-01-06_21_00_tags.txt.tbz2", "size":"1467"}]`

**Comment by Tysonpower** [comment]
okay thanks for all the information, will change that JS code to your suggestion and test it in the next weeks.
