### ISSUE TITLE
Add File Progress Indicator

### ISSUE THREAD

**Issue by Tysonpower** [Othernet-Project/Dreamcatcher#9]
Adding a File Download Progress Indicator would be nice, the older DC3 also had this and Users that had a look at the new UI also requested it. I think it would be useful 😃 

It looks like the ondd library already includes data for that (carousel.h):

```
unsigned int block_count	= 0;				// Total number of blocks in file
unsigned int block_recv		= 0;				// Blocks received thus far
```
Having this data in the Websocket would be all that is needed to show it on the UI.

PS: I wasn't able to find anything about ondd on Google, is it a special library made by/for Othernet?

**Comment by chegewara** [comment]
Yes, it is included, just i have to add callback with progress. It is for sure on the list TODO.

**Comment by chegewara** [comment]
Can be closed?

**Comment by Tysonpower** [comment]
> Can be closed?

will have a look at it as soon as the EU Beam is up and running :)
